Excercise from Google ML Crash Course Resources
NumPy UltraQuick Tutorial
NumPy is a Python library for creating and manipulating vectors and matrices. 

In [2]:
#Import NumPy module
#Run the following code cell to import the NumPy module:
import numpy as np

In [3]:
#Populate arrays with specific numbers
#Call np.array to create a NumPy matrix with your own hand-picked values. 
# For example, the following call to np.array creates an 8-element vector:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])

In [4]:
print(one_dimensional_array)

[ 1.2  2.4  3.5  4.7  6.1  7.2  8.3  9.5]


In [6]:
# You can also use np.array to create a two-dimensional matrix. 
#To create a two-dimensional matrix, specify an extra layer of square brackets. 
#For example, the following call creates a 3x2 matrix:
two_dimensional_array = np.array([[6,5],[11,7],[4,8]])

In [7]:
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [8]:
#To populate a matrix with all zeroes, call np.zeros. To populate a matrix with all ones, call np.ones.
b = np.zeros(2, dtype = int) 
print(b)

[0 0]


In [10]:
ab = np.zeros([2,2], dtype = int) 
print(ab)

[[0 0]
 [0 0]]


In [12]:
abc = np.zeros([3,2], dtype = float) 
print(abc)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [13]:
a1 = np.ones(3)
print(a1)

[ 1.  1.  1.]


In [14]:
b1 = np.ones([2,3], dtype=int)
print(b1)

[[1 1 1]
 [1 1 1]]


In [16]:
#Populate arrays with sequences of numbers
#You can populate an array with a sequence of numbers:
seq = np.arange(5,12)
print(seq)

[ 5  6  7  8  9 10 11]


In [17]:
seq2 = np.arange(2.5, 5.5)

In [18]:
print(seq2)

[ 2.5  3.5  4.5]


In [19]:
seq3 = np.arange(2.5, 5.5, step=0.5)
print(seq3)

[ 2.5  3.   3.5  4.   4.5  5. ]


Notes: Notice that np.arange generates a sequence that includes the lower bound but not the upper bound.
Use parameter step to indicate step size

### Populate arrays with random numbers
NumPy provides various functions to populate matrices with random numbers across certain ranges. For example, np.random.randint generates random integers between a low and high value. The following call populates a 6-element vector with random integers between 50 and 100.

In [21]:
random = np.random.randint(low=50, high=101, size=(6))
print(random)

[64 82 51 87 91 93]


Note that the highest generated integer np.random.randint is one less than the high argument.

To create random floating-point values between 0.0 and 1.0, call np.random.random. For example:

In [23]:
rand_float = np.random.random([5])
print(rand_float)

[ 0.7209918   0.76459784  0.04408326  0.6146125   0.65192509]


In [26]:
rand_float2 = np.random.random(5)
print(rand_float2)

[ 0.10875254  0.88872531  0.30423494  0.30687952  0.94011674]


In [27]:
rand_float3 = np.random.random([2,5])
print(rand_float3)

[[ 0.36264278  0.0257687   0.370468    0.16471863  0.01286817]
 [ 0.64075921  0.91126185  0.56410659  0.82419996  0.98214451]]


Note: random.random returns random floats in the half-open interval [0.0, 1.0).
Use random_sample  when specifying interval 

In [35]:
rand_float4 = np.random.random_sample((3, 2)) - 5
print(rand_float4)

[[-4.16275831 -4.56657962]
 [-4.74168957 -4.29955775]
 [-4.63926168 -4.6505386 ]]


In [36]:
rand_float5 = np.random.random_sample((4,4)) - 2
print(rand_float5)

[[-1.69424223 -1.16835925 -1.41747343 -1.64703408]
 [-1.42145504 -1.96301308 -1.45404344 -1.0596026 ]
 [-1.46210993 -1.48860033 -1.08025073 -1.55203998]
 [-1.96780224 -1.63906926 -1.39378321 -1.79502054]]


Mathematical Operations on NumPy Operands
If you want to add or subtract two vectors or matrices, linear algebra requires that the two operands have the same dimensions. Furthermore, if you want to multiply two vectors or matrices, linear algebra imposes strict rules on the dimensional compatibility of operands. Fortunately, NumPy uses a trick called broadcasting to virtually expand the smaller operand to dimensions compatible for linear algebra. For example, the following operation uses broadcasting to add 2.0 to the value of every item in the vector created in the previous code cell:

In [38]:
print(rand_float3 + 1)

[[ 1.36264278  1.0257687   1.370468    1.16471863  1.01286817]
 [ 1.64075921  1.91126185  1.56410659  1.82419996  1.98214451]]


In [40]:
print(seq*5)

[25 30 35 40 45 50 55]


Task 1: Create a Linear Dataset
Your goal is to create a simple dataset consisting of a single feature and a label as follows:

Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.
Assign 15 values to a NumPy array named label such that:

In [41]:
feature = np.arange(6, 21)
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [42]:
label = 3*feature +4

In [43]:
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


Task 2: Add Some Noise to the Dataset
To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created. To be more precise, modify each value assigned to label by adding a different random floating-point value between -2 and +2.

Don't rely on broadcasting. Instead, create a noise array having the same dimension as label.

In [52]:
noise = np.random.random_sample((15))  -2

In [53]:
print(noise)

[-1.35594862 -1.0083958  -1.63562764 -1.39499318 -1.40355116 -1.90365074
 -1.75559233 -1.49004534 -1.3823354  -1.54146804 -1.93962214 -1.08147879
 -1.87364057 -1.77720651 -1.18104065]


In [54]:
print(label + noise)

[ 20.64405138  23.9916042   26.36437236  29.60500682  32.59644884
  35.09634926  38.24440767  41.50995466  44.6176646   47.45853196
  50.06037786  53.91852121  56.12635943  59.22279349  62.81895935]
